[project]
name = "taskflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "psycopg>=3.3.6",
    "pydantic>=2.13.4",
    "pydantic-core==2.46.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.1",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
