"""Updated token hash to accept any length of chatacters

Revision ID: 68917d50c110
Revises: 260b705ef548
Create Date: 2026-10-01 15:33:01.951627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68917d50c110"
down_revision: Union[str, Sequence[str], None] = "260b705ef548"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_verifications",
        "tokenHash",
        existing_type=sa.String(length=6),
        type_=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
